language: node_js
node_js:
- '6'
- '7'
branches:
  only:
  - master
  - develop
  - /^v?(\d\.){2}\d$/
  - /^greenkeeper-.*$/
notifications:
  email:
  - nfantone@gmail.com
cache:
  bundler: true
  directories:
  - node_modules
script: npm run validate && ./node_modules/.bin/codecov
before_script:
- npm install codecov
deploy:
  provider: npm
  email: nfantone@gmail.com
  api_key:
    secure: IlIQt6H0//xJrNvMbp1txXdPM9Qjob0xNtfd+g0PqM2KUGcHnL5V4kq7qtViJavJgBK3zO6rRSdtYZk0uurkLyvl7E8PPcHcOOzfe6OAlK9Ul0js066+kq3K9y91F36nJuyw4NnvSUFSpttVreIKrmz9zxufIAJCsnXeT0zNpOPbaZbveM0dD7J7UUMxdpjKgAIESU5ivRRk7lxl5skzaRr03HNYTpQXTX6U9fcTf5LGIpA4STUJVOTl0aYlvRVT+fADFKJmxn74NPsGl8606OCTqjfuTUf2fKXr88IW0a5rT35yEBMdgtchckjyOw3x4df2PWDp/OKas0hypcYQ0uKUdw9F2yZbXKre42+/npyUh6+24tw778H9UVCllX+CvUu+f7JmsADPE4kQ6fGHlDrH+UqnrZURM+45St7MZbtEs4OpaNpyFeP5PiDa+yWkK9c/7JELOdtsnnntwjCG9ot4eZ5kLSS6EVvaJJXs4AsiiikIO80Ksobe5pBc0AaIEprRkK0RKD1gS/sTAu43f64CYGX/bAmyoS9CqeXBNmSgOY/dI+kQdqfi9B/jVFKCvaS4n8V+ZxTMNNu4j+sOSMtkoXtUiYjJsuNSPd9+BOy8J0X69BvJ9tgYPyaWTTvJfBnTu/kSf/xusm8WOzYWCxD4GJ7u37QT1WArlT0BK3g=
  on:
    tags: true
    repo: nfantone/mu-koan-logger
    node: '7'
