language: node_js
node_js:
- '5'
- '6'
only:
- master
- develop
notifications:
  email:
  - nfantone@gmail.com
cache:
  bundler: true
  directories:
  - node_modules
script: npm run validate && ./node_modules/.bin/codecov
before_script:
- npm install codecov
deploy:
  provider: npm
  email: nfantone@gmail.com
  api_key:
    secure: 0x3jePwOUnCz4ssysqkQg1XKIctAa4lvtx2KY761mBQK4nH4wzKiE5iMaK3QoGZgAAPCOGKLky3o5RTVuQbpwCLRQ4d0by2p3WhCXSHmM42Pe4Og57aA85LlG1brxtksoqPbbqCvxCgCi04yaNPc+s9jjywzPLny1IGuU49cLOX+lh5b6tHk9/mrzZHXIwdei47LhF5r1O3PFKP5WX5uKDe9kPTiT7zt4CEQZpfANXpSRqraAQZTtyDxuyOgoBZsoJCmjLQGXttWeXLeiMasSj57Zjq8wRSreMOdTOp/J0KaPK5W1YCQsmu5anuM7DmhmDs0A9DOewu/hQjVr3TlCsEYwNsJPdghNZvjlxv9XnNOCOo100adPc0Z1rKDBTkHxVAigRr+FSQ1fiYQx+1m+o7TUqb6ET9W/kxLMbUGL/5JgCaroyLCnRqUvP8A3vDftp0m37oWIZnnXqijtg//9Miab39xfeRkBfPpEUROXEQRwoV/4IhbBDjtJwZFxKY6vHGqO+596Rfmj04XEh/6pJtciDQQwESlANFt+ey0oxb0mLu7WtHfVWyguFNLnnCAwZBoOvZFkTgEZ3VwQq49MsPUO4O/8OkOn4hm43KbeIcMCB0/uF1Z2PuZSoPC9l93nXye8YlmkHTethyD7/K8vebQ5j/Zmy/08BVJsEsoju0=
  on:
    tags: true
    repo: nfantone/mu-koan-logger
